#!/bin/sh

ssh -p 20411 app@cpdev2 <<EOF
   cd /var/www/hello/trunk/
   git pull
   sudo service nginx restart
   sudo service php5-fpm restart
   sudo service varnish restart
   sudo service pound restart 
   exit
EOF
